---
title: "Speciale_analysis"
author: "Martin Andersen"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load packages:
library(tidyverse)
library(lubridate)
library(readxl)
library(timetk)
library(dplyr)
library(zoo)
```

First we download the data that we want to work with:
```{r}
data <- read.csv("C:/Users/Marti/OneDrive - University of Copenhagen/KU/Speciale/Data behandling/all_data_weekly.csv", sep = ",") %>%
  select(-X) %>%
  mutate(date = as.Date(date)) %>% 
  arrange(isin) %>%
  replace(is.na(.), 0) #Replace NA's with zero's as this simply means no signal this week
```

Calculate moving averages of the sentiment data
```{r}
source("functions.R")

rollmean_sentiment_data <- function_rolling_mean(dataset = data, periods = 2) %>% select(-c(PX_LAST,W_RETURN,MKT_CAP))
  
```



The function: "assign_portfolio" allows a specific variable (SGD sentiment) and the number of portfolios to divide a dataset into portfolio sorts: 
```{r}

```
